name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          # - windows-latest
          # - windows-11-arm
          # - macos-15-intel
          - macos-14

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          MACOSX_DEPLOYMENT_TARGET: "14.0"
          CIBW_ENVIRONMENT_MACOS: 'CPPFLAGS="-I/opt/homebrew/include/" LDFLAGS="-L/opt/homebrew/lib/ -static"'
          CIBW_ENVIRONMENT_LINUX: 'CPPFLAGS="-I/opt/pyca/cryptography/openssl/include/" LDFLAGS="-L/opt/pyca/cryptography/openssl/lib64/"'
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/pyca/cryptography-manylinux2014:x86_64
          CIBW_MUSLLINUX_X86_64_IMAGE: ghcr.io/pyca/cryptography-musllinux_1_2:x86_64

      - uses: actions/upload-artifact@v6
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
