name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
        os:
          - ubuntu-latest
          # - ubuntu-24.04-arm
          # - windows-latest
          # - windows-11-arm
          # - macos-15-intel
          - macos-14

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false


      - name: Set up compiler flags
        run: |
            if [ "${{ runner.os }}" == "macOS" ]; then
              echo 'CPPFLAGS="-I/opt/homebrew/include/"' >> $GITHUB_ENV
              echo 'LDFLAGS="-L/opt/homebrew/lib/"' >> $GITHUB_ENV
            else
              echo 'CPPFLAGS="-I/opt/pyca/cryptography/openssl/include/"' >> $GITHUB_ENV
              echo 'LDFLAGS="-L/opt/pyca/cryptography/openssl/lib64/"' >> $GITHUB_ENV
            fi
            echo "CPPFLAGS: ${{ env.CPPFLAGS }}"
            echo "LDFLAGS: ${{ env.LDFLAGS }}"
        shell: bash

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          MACOSX_DEPLOYMENT_TARGET: "14.0"
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/pyca/cryptography-manylinux2014:x86_64
          CIBW_MUSLLINUX_X86_64_IMAGE: ghcr.io/pyca/cryptography-musllinux_1_2:x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
